name: Quick issue or idea
description: Use this form to tell us about a bug, a problem, a feature request, or an idea.
title: "[Issue]: "
labels: ["triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Give your report a short title
      description: One short sentence that says what happened or what you want.
      placeholder: e.g. Total is wrong on invoice page
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: What is this?
      description: Pick the closest option so we know how to handle it.
      options:
        - "Bug (something is broken)"
        - "Problem (something is confusing or not working as expected)"
        - "Feature request (a new thing you'd like)"
        - "Idea / suggestion (a smaller improvement)"
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: How much does this affect you?
      options:
        - "Low — small or cosmetic"
        - "Medium — affects some users or workflows"
        - "High — blocks important work for many users"
        - "Critical — stops the whole product or causes data loss"
    validations:
      required: false

  - type: input
    id: where
    attributes:
      label: Where did you see this?
      placeholder: "e.g. website > Checkout, mobile app > iPhone 12"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: What did you do? (Steps)
      placeholder: "1. Go to ...  2. Click ...  3. See ..."
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: What happened?
      description: Describe what you saw vs what you expected.
    validations:
      required: false

  - type: checkboxes
    id: reporter_checks
    attributes:
      label: Quick checklist
      options:
        - label: "I looked for similar reports"
          required: false
        - label: "I removed any private information"
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 📮 What happens next?
        
        > [!NOTE]
        > Once submitted, your report is tagged with **triage**. Our team reviews these daily to ensure nothing gets missed.

        ### 🔄 Our Process
        1. **Classification:** We confirm if it's a bug, feature, or idea.
        2. **Prioritization:** We set the urgency and assign a team member.
        3. **Clarification:** If we're stuck, we'll comment with clear "next steps" for you.
        4. **Cleanup:** Once reviewed, the `triage` label is replaced with a status label.

        ### 💡 Pro-Tips for a Great Report
        * **Visuals:** Screenshots or screen recordings are 10x better than text. (Loom is great!)
        * **Context:** Mentioning your browser or device saves us a lot of guessing.
        * **Links:** If this is related to another issue, paste the `#issue-number`.

        ---
        *Thank you for helping us improve Sosana.io!*
