name: Quick issue or idea
description: Use this form to tell us about a bug, a problem, a feature request, or an idea.
title: "[Issue]: "
labels: ["triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Give your report a short title
      description: One short sentence that says what happened or what you want.
      placeholder: e.g. Total is wrong on invoice page
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: What is this?
      description: Pick the closest option so we know how to handle it.
      options:
        - "Bug (something is broken)"
        - "Problem (something is confusing or not working as expected)"
        - "Feature request (a new thing you'd like)"
        - "Idea / suggestion (a smaller improvement)"
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: How much does this affect you?
      options:
        - "Low — small or cosmetic"
        - "Medium — affects some users or workflows"
        - "High — blocks important work for many users"
        - "Critical — stops the whole product or causes data loss"
    validations:
      required: false

  - type: input
    id: where
    attributes:
      label: Where did you see this?
      placeholder: "e.g. website > Checkout, mobile app > iPhone 12"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: What did you do? (Steps)
      placeholder: "1. Go to ...  2. Click ...  3. See ..."
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: What happened?
      description: Describe what you saw vs what you expected.
    validations:
      required: false

  - type: checkboxes
    id: reporter_checks
    attributes:
      label: Quick checklist
      options:
        - label: "I looked for similar reports"
          required: false
        - label: "I removed any private information"
          required: false

  - type: markdown
    attributes:
      value: |
        ### What usually happens after you send a report
1. It gets the “triage” label so our team sees it in the review list.
2. Someone reads it and:
   - Confirms the kind of report (bug / feature / idea).
   - Adds a clear label (for example, bug or feature) and sets how urgent it is.
   - Asks for more information if needed (we’ll say exactly what we need).
   - Assigns it to a person and considers next steps.
3. After a first review, the "triage" label is removed.

How you can help
- Add a short title and one-sentence summary.
- If you can, add steps and a screenshot — those help a lot.
- Say where you saw it (website, app, page name).
- If you find something similar, add a link to that report.

If we need more from you, we’ll ask with simple, clear steps to help us reproduce or understand the issue.
